[project]
name = "cipo"
version = "0.1.0"
description = "Retrieving and analyzing unconfirmed objects from Minor Planet Center"
readme = "README.md"
authors = [ 
    { name = "Lucas Correa de Souza", email = "lucascorreasouza@id.uff.br" },
    { name = "Mario De Pra", email = "depra@on.br" }
]
requires-python = ">=3.13"
dependencies = [
    "astropy>=7.2.0",
    "beautifulsoup4>=4.12.0",
    "html5lib>=1.1",
    "lxml>=6.0.2",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "selenium>=4.36.0",
    "skyfield>=1.53",
    "webdriver-manager>=4.0.2",
]

[project.optional-dependencies]
dev = [
    "jupyter>=1.1.1",
]

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"

